# Generated by Django 4.0.4 on 2022-04-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(max_length=50)),
                ('oppNumber', models.CharField(blank=True, max_length=25)),
                ('name', models.CharField(max_length=100)),
                ('prodCode', models.CharField(max_length=6)),
                ('request', models.CharField(max_length=25)),
                ('sales', models.CharField(max_length=25)),
                ('projManager', models.CharField(max_length=25)),
                ('engineer', models.CharField(max_length=25)),
                ('reqDate', models.DateTimeField(blank=True, null=True)),
                ('dueDate', models.DateTimeField(blank=True, null=True)),
                ('compDate', models.DateTimeField(blank=True, null=True)),
                ('comments', models.CharField(blank=True, max_length=1000)),
            ],
        ),
    ]
