# Generated by Django 4.0.4 on 2022-04-28 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='compDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='master',
            name='dueDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='master',
            name='reqDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
