# Generated by Django 4.0.4 on 2022-05-04 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activityAPI', '0004_alter_master_compdate_alter_master_duedate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='compDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='master',
            name='dueDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='master',
            name='reqDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=True, verbose_name='ID')),
                ('entry_date', models.DateTimeField(auto_now=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activityAPI.master')),
            ],
        ),
    ]
